In [1]:
import pandas as pd
import numpy as np

In [2]:
file_name="https://s3.us.cloud-object-storage.appdomain.cloud/cf-courses-data/CognitiveClass/DP0701EN/version-2/Data-Collisions.csv"
df=pd.read_csv(file_name)
df.shape

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (33) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


(194673, 38)

In [3]:
df.head()

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY REPORTNO  \
0             2 -122.323148  47.703140         1    1307       1307  3502005   
1             1 -122.347294  47.647172         2   52200      52200  2607959   
2             1 -122.334540  47.607871         3   26700      26700  1482393   
3             1 -122.334803  47.604803         4    1144       1144  3503937   
4             2 -122.306426  47.545739         5   17700      17700  1807429   

    STATUS      ADDRTYPE   INTKEY  ... ROADCOND                LIGHTCOND  \
0  Matched  Intersection  37475.0  ...      Wet                 Daylight   
1  Matched         Block      NaN  ...      Wet  Dark - Street Lights On   
2  Matched         Block      NaN  ...      Dry                 Daylight   
3  Matched         Block      NaN  ...      Dry                 Daylight   
4  Matched  Intersection  34387.0  ...      Wet                 Daylight   

  PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
0           NaN         NaN      NaN         10   
1           NaN   6354039.0      NaN         11   
2           NaN   4323031.0      NaN         32   
3           NaN         NaN      NaN         23   
4           NaN   4028032.0      NaN         10   

                                          ST_COLDESC  SEGLANEKEY  \
0                                  Entering at angle           0   
1  From same direction - both going straight - bo...           0   
2                             One parked--one moving           0   
3                   From same direction - all others           0   
4                                  Entering at angle           0   

   CROSSWALKKEY  HITPARKEDCAR  
0             0             N  
1             0             N  
2             0             N  
3             0             N  
4             0             N  

[5 rows x 38 columns]

In [16]:
predictor_df=df[["SEVERITYCODE","WEATHER","ROADCOND","LIGHTCOND"]] # predictor variables for predicting severity


In [17]:
predictor_df["WEATHER"] = predictor_df["WEATHER"].astype('category')
predictor_df["ROADCOND"] = predictor_df["ROADCOND"].astype('category')
predictor_df["LIGHTCOND"] = predictor_df["LIGHTCOND"].astype('category')

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try usi

In [18]:
predictor_df["WEATHER_CAT"] = predictor_df["WEATHER"].cat.codes
predictor_df["ROADCOND_CAT"] = predictor_df["ROADCOND"].cat.codes
predictor_df["LIGHTCOND_CAT"] = predictor_df["LIGHTCOND"].cat.codes

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/ipykernel/__main__.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try usi

In [19]:
predictor_df.dtypes


SEVERITYCODE        int64
WEATHER          category
ROADCOND         category
LIGHTCOND        category
WEATHER_CAT          int8
ROADCOND_CAT         int8
LIGHTCOND_CAT        int8
dtype: object

In [20]:
predictor_df["WEATHER"].value_counts()


Clear                       111135
Raining                      33145
Overcast                     27714
Unknown                      15091
Snowing                        907
Other                          832
Fog/Smog/Smoke                 569
Sleet/Hail/Freezing Rain       113
Blowing Sand/Dirt               56
Severe Crosswind                25
Partly Cloudy                    5
Name: WEATHER, dtype: int64

In [21]:
predictor_df["SEVERITYCODE"].value_counts()


1    136485
2     58188
Name: SEVERITYCODE, dtype: int64

In [22]:
predictor_df["ROADCOND"].value_counts()


Dry               124510
Wet                47474
Unknown            15078
Ice                 1209
Snow/Slush          1004
Other                132
Standing Water       115
Sand/Mud/Dirt         75
Oil                   64
Name: ROADCOND, dtype: int64

In [10]:
predictor_df["LIGHTCOND"].value_counts()


Daylight                    116137
Dark - Street Lights On      48507
Unknown                      13473
Dusk                          5902
Dawn                          2502
Dark - No Street Lights       1537
Dark - Street Lights Off      1199
Other                          235
Dark - Unknown Lighting         11
Name: LIGHTCOND, dtype: int64

In [23]:
from sklearn.utils import resample


In [24]:
df_firstrow = predictor_df[df.SEVERITYCODE==1]
df_secondrow = predictor_df[df.SEVERITYCODE==2]

df_secondrow_sampling = resample(df_firstrow,
                              replace=False,
                              n_samples=58188,
                              random_state=101)

df_balanced = pd.concat([df_secondrow_sampling, df_secondrow])

df_balanced.SEVERITYCODE.value_counts()

2    58188
1    58188
Name: SEVERITYCODE, dtype: int64

In [25]:
X = np.asarray(df_balanced[['WEATHER_CAT', 'ROADCOND_CAT', 'LIGHTCOND_CAT']])
X[0:5]

array([[1, 0, 5],
       [6, 8, 2],
       [6, 8, 5],
       [1, 0, 5],
       [1, 0, 5]], dtype=int8)

In [26]:
Y= np.asarray(df_balanced['SEVERITYCODE'])
Y[0:5]

array([1, 1, 1, 1, 1])

<h1>Preprocessing the Data<h1>


In [27]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-0.67442339, -0.66970285,  0.4283633 ],
       [ 1.15179995,  1.53032436, -1.21915665],
       [ 1.15179995,  1.53032436,  0.4283633 ],
       [-0.67442339, -0.66970285,  0.4283633 ],
       [-0.67442339, -0.66970285,  0.4283633 ]])

<h1>Model and Evaluation<h1>


In [28]:
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=4)   # creating test and train set
print ('Train sets:', X_train.shape[0])
print ('Test sets:', X_test.shape[0])

Train sets: 81463
Test sets: 34913


<h3>kNN<h3>

In [30]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

Ks=10
mean_acc=np.zeros((Ks-1))
std_acc=np.zeros((Ks-1))
ConfusionMatrix=[]
for n in range(1,Ks):
    neigh = KNeighborsClassifier(n_neighbors=n).fit(X_train, Y_train)
    yhat = neigh.predict(X_test)
    mean_acc[n-1] = metrics.accuracy_score(Y_test, yhat)
    std_acc[n-1] = np.std(yhat==Y_test)/np.sqrt(yhat.shape[0])
mean_acc

array([0.55200069, 0.54472546, 0.54234812, 0.5449546 , 0.55182883,
       0.5465013 , 0.5467018 , 0.5465013 , 0.54627216])

In [31]:
print( "The best accuracy was with", mean_acc.max(), "with k=", mean_acc.argmax()+1)


The best accuracy was with 0.552000687423023 with k= 1


<h3>knn evaluation<h3>

In [33]:
knn_yhat = neigh.predict(X_test)


jaccard_score(Y_test, knn_yhat)


0.23779050185247558

In [34]:
f1_score(Y_test, knn_yhat, average='macro')


0.5125097414762372

<h4>Decision Tree<h4>

In [36]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion="entropy", max_depth = 7)

dt.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=7)

In [38]:
dt_y_pred = dt.predict(X_test)


<h3>Decision Tree Evaluation<h3>

In [39]:
jaccard_score(Y_test, dt_y_pred)


0.2856941574300207

In [40]:
f1_score(Y_test, dt_y_pred, average='macro')


0.5430741006902506

<h3>Logistic Regression<h3>

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=6, solver='liblinear').fit(X_train,Y_train)

In [42]:
LR_y_pred = LR.predict(X_test)


In [43]:
LR_y_prob = LR.predict_proba(X_test)


In [45]:
LR_y_prob = LR.predict_proba(X_test)
log_loss(Y_test, LR_y_prob)

0.684679793585963

<h3>Logistic Regression Evaluation<h3>

In [46]:
jaccard_score(Y_test, LR_y_pred)


0.277022568298799

In [47]:
f1_score(Y_test, LR_y_pred, average='macro')


0.5155215511318116

In [48]:
from sklearn.metrics import accuracy_score
print("KNN Accuracy: ", accuracy_score(Y_test, knn_yhat))

KNN Accuracy:  0.5462721622318334


In [50]:
print("Decision Tree Accuracy: ", accuracy_score(Y_test, dt_y_pred))


Decision Tree Accuracy:  0.5643743018359924


In [52]:
print("Logistic Regression Accuracy: ", accuracy_score(Y_test, LR_y_pred))


Logistic Regression Accuracy:  0.5292870850399565
